### ISSUE TITLE
Measure widths - crosshairs

### ISSUE THREAD

**Issue by brianstirling** [ZappyMan/MorphoMetriX-V2#13]
When measuring body widths of relatively small animals (e.g., a dolphin calf) at relatively high altitudes (e.g., > 30 m) the crosshairs obscure the contour of the animal when set at any size, making it difficult to precisely align subsequent points. The issue may be resolved by decreasing the minimum allowable crosshair size, making the crosshair icons transparent, or enabling the option to choose a different crosshair type (e.g., a single dot). Thank you.
![Screenshot 2023-10-12 103116](https://github.com/ZappyMan/MorphoMetriX-V2/assets/63370653/b8477bb9-b7ad-424e-8bfe-ee2a1d13413a)

**Comment by ZappyMan** [comment]
This issue is most likely due to the dolphin being 50 - 100 pixels wide. The opacity and circle crosshair feature will be added, as well as increased range with size slider.

**Comment by ZappyMan** [comment]
Version 2.2.0 should address this issue.
