### ISSUE TITLE
MoprhoMetriX not working for Mac Os < 11.0.0

### ISSUE THREAD

**Issue by DGaspard2** [ZappyMan/MorphoMetriX-V2#14]
Software can be installed, but cannot open. Issue due to PyQt6 framework. Using Mac Os Catalina (10.15.7), intel chip. Tried opening software through terminal and this was the error message: Sorry, "MorphoMetriX" cannot be run on this version of macOS. Qt requires macOS 11.0.0 or later, you have macOS 10.15.7.

**Comment by ZappyMan** [comment]
PySide6 versions 6.4.3+ dropped support for Mac OS Catalina 10.X, will downgrade future versions to 6.4.3.

**Comment by ZappyMan** [comment]
Version 2.2.0 should solve this issue.
