### ISSUE TITLE
crosshairs too big if at altitude

### ISSUE THREAD

**Issue by CharlotteBahamas2017** [ZappyMan/MorphoMetriX-V2#16]
Hi - I can't get the crosshairs small enough when I am measuring a calf at an altitude of about 50m - see attached pic to demonstrate, thanks, Charlotte
<img width="1025" alt="Screenshot 2024-03-05 at 3 42 26 PM" src="https://github.com/ZappyMan/MorphoMetriX-V2/assets/30603126/6c45638a-54aa-4a36-a4e7-ce8436a96591">

**Comment by ZappyMan** [comment]
Hi Charlotte,
Which version of MorphoMetrix are you using? In version 2.2.0 theres the option to change the size and opacity of the crosshair. If this is version 2.2.0, and this is the smallest size you can make the crosshairs, then this issue will occur when the subject is less than  200 pixels wide. I would then recommend changing the style of the crosshairs to dot. 

Hope this helps!

**Comment by CharlotteBahamas2017** [comment]
Thank you! I can’t see how to tell which version, but don’t seem to be any options to change size
